sudo: false

language: scala

scala:
        - 2.11.6

script: "mvn test verify -Dmaven.javadoc.skip=true"

jdk:
        - openjdk8
        - openjdk9
        - openjdk10
        - openjdk11

notifications:
    email:
        - digitalpreservation@nationalarchives.gov.uk
