sudo: false

language: scala

scala:
        - 2.11.6

script: "mvn test verify -Dmaven.javadoc.skip=true"

jdk:
        - openjdk7
        - openjdk8
        - oraclejdk8

notifications:
    email:
        - digitalpreservation@nationalarchives.gov.uk
